export const COLOURS = {
    BLACK: "#000",
    WHITE: "#FFF",
    ALMOST_WHITE: "#E0E0E0",
    DODGER_BLUE: "#428AF8",
    DODGER_BLUE_LIGHTER: "#99c2ff",
    DODGER_BLUE_DARKER: "#3260a4",
    DODGER_BLUE_DARK: "#1f70ea",
    LIGHT_SILVER: "#EEEEEE",
    SILVER: "#BEBEBE",
    TORCH_RED: "#F8262F",
    MISCHKA: "#E5E4E6",
    GOLDEN: "#FFD54F",
    PURPLE: "#AB47BC",
    CYAN: "#4DD0E1"
  };